apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      name: kubia-v1
    spec:
      replicas: 3
      template:
        metadata:
          name: kubia
          labels:
            app: kubia
        spec:
          containers:
            - image: gildas/kubia:1.0.0
              name:  nodejs
  - apiVersion: v1
    kind: Service
    metadata:
      name: kubia
    spec:
      #type: NodePort #LoadBalancer
      type: LoadBalancer
      selector:
        app: kubia
      ports:
        - port: 80
          targetPort: 8080
