apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      name: kubia-v1
    spec:
      replicas: 3
      template:
        metadata:
          name: kubia
          labels:
            app: kubia
        spec:
          containers:
            - image: gildas/kubia:1.0.0
              name:  nodejs
  - apiVersion: v1
    kind: Service
    metadata:
      name: kubia
    spec:
      type: LoadBalancer # Since I am running on docker Mac or minikube, there is no cloud's load balancer
      #type: NodePort      # So, we should use a NodePort
      selector:
        app: kubia
      ports:
        - name:       http
          port:       80
          targetPort: 8080
          protocol:   TCP
